### ISSUE TITLE
Can release a executable file?

### ISSUE THREAD

**Issue by wwhai** [emqx/qmqtt-client#16]
My pc not install qt5,hope release a executable app.

**Comment by mwallnoefer** [comment]
For the moment _qmqtt-client_ remains a software which has to be compiled from scratch on your platform, so we do not provide any binary releases.

If you are not able/allowed to install Qt5 and do the compilation you may use other Mqtt GUI clients, there exist plenty of them including websocket-based browser plugins (e.g. HiveMQ).

@ejvr Would you like to add something?

**Comment by ejvr** [comment]
Sadly I cannot comment. Right now I'm far away from home and internet access is rather limited. I can take a look at this after januari 10.

-------- Original Message --------

**Comment by ejvr** [comment]
Creating binaries would be a lot of work. You'll have to cover several QT versions and several platforms. There are probably ways to simplify the process using some kind of build farm, like github Actions, but I have never used that to deploy dll's or executables.

**Comment by mwallnoefer** [comment]
This issue could be closed as _WON'T DO_. Just that I do not seem to have any permissions to do so.
